### LABORATORIO 4
### LABORATORIO 4
### AUTORES MATÍAS MARTIN E IVO DI MARCO
### AUTORES MATÍAS MARTIN E IVO DI MARCO
### LINK DEL REPOSITORIO DE GITHUB: 
### LINK DEL REPOSITORIO DE GITHUB: 

import tkinter as tk

print("Bienvenido al Laboratorio 4 de Matías Martin e Ivo Di Marco")